[package]
name = "talk"
version = "0.1.0"
authors = ["Maiddog <maiddogsrl@gmail.com>"]

[dependencies]
serde_json = "1.0"

[dependencies.rusqlite]
version = "0.12"
features = ["bundled", "serde_json"]