[package]
name = "talk"
version = "0.1.0"
authors = ["Maiddog <maiddogsrl@gmail.com>"]

[dependencies]
ngrams = "1.0"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rusqlite]
version = "0.12"
features = ["bundled", "serde_json"]